---
apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: PlacementRule
metadata:
  name: managed-openshift-clusters
  namespace: policies
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: vendor
          operator: "In"
          values:
          - OpenShift
        - key: local-cluster
          operators: "NotIn"
          values:
          - true