apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: anmazon-cloudwatch-placement-1
  namespace: anmazon-cloudwatch 
  labels:
    app: anmazon-cloudwatch
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions: []
    matchLabels:
      # Replace value with Cluster you wish to provision too.
      name: managed-roks-1 