global:
  tlsDisable: false
  openshift: true

clusterNames:
  - cluster0
  - cluster1
  - cluster2

rootca_crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURHVENDQWdHZ0F3SUJBZ0lSQUxQY2hwZGliYTlNYzZHY3AvNnJtckV3RFFZSktvWklodmNOQVFFTEJRQXcKSmpFa01DSUdBMVVFQXhNYlkyRXVjMlZzWmkxemFXZHVaWEl1WTJWeWRDMXRZVzVoWjJWeU1CNFhEVEl5TURFeApNekl6TXpJeU1Gb1hEVEl5TURReE16SXpNekl5TUZvd0pqRWtNQ0lHQTFVRUF4TWJZMkV1YzJWc1ppMXphV2R1ClpYSXVZMlZ5ZEMxdFlXNWhaMlZ5TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEKeXNzTHBQNnN6YlA1WStLK3BqZ2dZZ05WYmJUQ2dmSnIyWUhhNUhpRkdnN2I3cU9NTFBwYzN0dnh4dFV0ZTdQbgpBc3g0b0hyU0V2ZFNDVU1Ubmc5MGdlQ1BFcnJHajZxcnk4VzQ0UVJsa1hBTTFWVGltTDhaT2VWLzNLdUw4SDNwCjczSW01ZFVueXVlZDJIZWtPSzNqOG9Dc3dxVjlNQ2RjOG83YkJRSENmNXhjQkg4U204Y2hUZ0JoRGZiWjhUQk4KN2dWZGt0L015TmZaTVp4aFBQVW4rWUFRNlB5bG1ndThvU3BCTGlteldIb3IzR0ZwajNmc1BkQlpvbXZLeEpYWAp6aXF3cjFjVFFncVRIRXhsTllad01Ia2plb0RFNHBkR0E1R0hIRE9EQ2ErUWdYeG01cTA2Nng3cUpQYTY3czVBCnZkQnZHbk05aFl1QUFhQkVEUWg1TndJREFRQUJvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBcVF3RHdZRFZSMFQKQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVTh4K3dEZmdudXpHZzB4eFB4bnJCSVBlT09uMHdEUVlKS29aSQpodmNOQVFFTEJRQURnZ0VCQUgvak5kZnJrWGNWVjhlOVFNc3Z4ZTRxaXNRQXRSOEtJNWVvZllReXBHemhYdURTCm1Fc3AwcGZCT0gyQ083TW03RE02NmxnNFBMVzNJSmlZRDgxN1JhbENsY1IxSTJMYk4yczErOTB6ODF1TWRPekgKYnVsWXdHUExuamZHazJtSEJkclN5Yk1FaXJJQzdYcGF1cmhvNFVFdDJxcm1qK2FkZWsxRis5ZW40cmxaVVVpVwo2anBIZ3hQSVViMnpzWWNvdEt3anNvYmx4M05RdFhlNDJMVzQ4ZUZGcEloTHlKdDZMVitiYUlzYlVrUkN6Um1LCk9tb29vdThKNGxVVldNQVRsR2FQMUR1MTI1SHpEcjVDdTByb0NPRkJVY2JaVzBLTUF4Q21BbVRENCtNNVl5ZEEKYnlhWGVMUldUZU1BZFhpait0SXRaT3pycm90U3hlbWRGaHN0OHQ0PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg== 
rootca_key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBeXNzTHBQNnN6YlA1WStLK3BqZ2dZZ05WYmJUQ2dmSnIyWUhhNUhpRkdnN2I3cU9NCkxQcGMzdHZ4eHRVdGU3UG5Bc3g0b0hyU0V2ZFNDVU1Ubmc5MGdlQ1BFcnJHajZxcnk4VzQ0UVJsa1hBTTFWVGkKbUw4Wk9lVi8zS3VMOEgzcDczSW01ZFVueXVlZDJIZWtPSzNqOG9Dc3dxVjlNQ2RjOG83YkJRSENmNXhjQkg4UwptOGNoVGdCaERmYlo4VEJON2dWZGt0L015TmZaTVp4aFBQVW4rWUFRNlB5bG1ndThvU3BCTGlteldIb3IzR0ZwCmozZnNQZEJab212S3hKWFh6aXF3cjFjVFFncVRIRXhsTllad01Ia2plb0RFNHBkR0E1R0hIRE9EQ2ErUWdYeG0KNXEwNjZ4N3FKUGE2N3M1QXZkQnZHbk05aFl1QUFhQkVEUWg1TndJREFRQUJBb0lCQUVyUzhqLzFxK0xXTmYxeAo2ekEvWTB0bXVYMmFCVzZXK000dlNJbW1JazVFRDBnVTFpSytXY2ZzMVYrc3huUnZJNXgzdjBaUEt2WE9oVmxmCmczeDliVnFDZGFmT2ZIY0QzUkY1cWNaMHJka2t3OGR1NDVEQ2FkZGY0M2FUWVRYaDc0L215WTFod2FYdkllRjkKKzN6aVJFbjB5a21qYi9aMWY2a0xwcXBKUk85NkpLQkt1cXR5aEZld2ovS2Z6ZlZVVlUyRndOcElrT3ArU2YzMQprS2o1dXhZd1lFREN6cG9pY3dTSVRmbEkxKytwMGxIUTc3UVQ5eldJTUM1SCs5TTNSNnh2NG5kK0JscjJUZisvCkNqaUlQQWpQRlFRMlpFTmFSdTVMbEdvRlNUSDd1NmVRbzNKc29RbGhRcFE2YWtwaFlRdzVrVzJnc2U0akhTM1YKelorckdPRUNnWUVBNGYzd2NQaURiTXYzSGROeW9ZVzVTZ2VNV2czZy8wOGxJNzR2UmNPR09LcEg5L3dscVprawpBU3hOYjNnRUU3SmlsSisvTHRjdVNiczVOQXgxSmpCSHAzKzRzMWpsUXVodmJPV3VXUWoraFkxaCtQK2dQV0k1Cmg3ZzBQZkpQQXdrYVNEQTEwYWJGM0FPT09BT05JNytBa01uV1I5QkkzZkJxSzRQZ1h1RWNyRWNDZ1lFQTViaUUKbGJ4OXE1SUxZa0d2dHlud29VWmpoTDN0Uk15QmpJMGxjdnEwZFRPdGl2eDBhQmg3Uk1TT2lPdTlTY05iVUpyNwpGRDlJb3ZoOTNsZVMxRVZXVWc5cWZzSHkxa3pKL0Z6enJKUlhLemRibEhDOXZHZ1FUdXp2WXhXY2hKVmh0OGh5CjBJdTNHYnJxM1Q3WUNaUGNVYTU2amQwR1R3bUFCcDExRXNEaGM1RUNnWUVBM3BNZDFnWE1Xc0RmbDA2RG5iVjQKY2dMUkpuaDQycnIyVnllZW8xVVl3b0ppODBneFI4SCtCZkcrS2tUSHJ5YUhsTjFvakJkK0RUd0o4TXM4TGVwcgpCL3J3ekNLSFdjaFd4YWZJZVFRMHVSQXdKKzZMd1NrV2hDYlZ2UlVDNEhoOG5CQnZVUmF4MUNqa1R5S2dSVTc4CnJwMDdIK3R4ZUxTcHZFWGNHMVlXeVUwQ2dZQkR4ZTlmMmM5ZHVlV2Y1Rzg1NDZhNWZmSEliTncrYXZOaGl4YmMKV0RpN1J6YlJCWEEyY2RxVVRFVWRBaWZEUmw1L1ptbmk3RlM2dUFNeWdMV3g2STd5QU5oVGMxYjRnSWtxNmlWOQo2Zm5acHloZW4vQnFVRzFYUzdISWtzeXRsUURTWHRINDB1OS9LTlUzMXQyWDNjYW5Wb21UcHZ6QWZyWUZ2WmlYCm9zNGc4UUtCZ1FEYlBvMXRNdytFRjkyWkhLSUFBQVNkK2x1alh4Rnd6VzVMZTJCMUtKbHlUODkvcWxQQUdFT2IKYytYSkwwNnpmR2ZIV0F4Z09SVlpPQXRHVXh4SWZ2OW5udUNhdlZGUGlTWG1tTE5rYUxnNWhMNTNaMnVOVVRRUwpTZUxiL1dNVWlIa2NkbVpmYjR1ZjhMNmNVYlNXV0ZpOW56bC9vM2dNUWg4WFBNeFF3NnRKWlE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
global_base_domain: global.ibmsbaasonaws.com 

vault:  
  ui:
    enabled: true
  server:
    image: 
      tag: 1.8.1
    multicluster:
      enabled: enabled 
      cluster: aws-cluster-shared-2
    extraVolumes:
      - type: 'secret'
        name: 'vault-tls'
        path: '/etc'                 
    ha:
      replicas: 3
      enabled: true
      raft:
        enabled: true
        setNodeId: true
        config: |
          ui = true

          listener "tcp" {
            address = "[::]:8200"
            cluster_address = "[::]:8201"
            tls_cert_file="/etc/vault-tls/tls.crt"
            tls_key_file="/etc/vault-tls/tls.key"
            tls_client_ca_file="/etc/vault-tls/ca.crt"          
          }

          storage "raft" {
            path = "/vault/data"
    
            retry_join {
              leader_api_addr = "https://vault-0.aws-cluster-shared-0.vault-internal.vault.svc.clusterset.local:8200"
              leader_ca_cert_file = "/etc/vault-tls/ca.crt"
            }

            retry_join {
              leader_api_addr = "https://vault-1.aws-cluster-shared-0.vault-internal.vault.svc.clusterset.local:8200"
              leader_ca_cert_file = "/etc/vault-tls/ca.crt"
            }

            retry_join {
              leader_api_addr = "https://vault-2.aws-cluster-shared-0.vault-internal.vault.svc.clusterset.local:8200"
              leader_ca_cert_file = "/etc/vault-tls/ca.crt"
            }            

            retry_join {
              leader_api_addr = "https://vault-0.aws-cluster-shared-1.vault-internal.vault.svc.clusterset.local:8200"
              leader_ca_cert_file = "/etc/vault-tls/ca.crt"
            }

            retry_join {
              leader_api_addr = "https://vault-1.aws-cluster-shared-1.vault-internal.vault.svc.clusterset.local:8200"
              leader_ca_cert_file = "/etc/vault-tls/ca.crt"
            }

            retry_join {
              leader_api_addr = "https://vault-2.aws-cluster-shared-1.vault-internal.vault.svc.clusterset.local:8200"
              leader_ca_cert_file = "/etc/vault-tls/ca.crt"
            }               

            retry_join {
              leader_api_addr = "https://vault-0.aws-cluster-shared-2.vault-internal.vault.svc.clusterset.local:8200"
              leader_ca_cert_file = "/etc/vault-tls/ca.crt"
            }

            retry_join {
              leader_api_addr = "https://vault-1.aws-cluster-shared-2.vault-internal.vault.svc.clusterset.local:8200"
              leader_ca_cert_file = "/etc/vault-tls/ca.crt"
            }      

            retry_join {
              leader_api_addr = "https://vault-2.aws-cluster-shared-2.vault-internal.vault.svc.clusterset.local:8200"
              leader_ca_cert_file = "/etc/vault-tls/ca.crt"
            }                              

          }

          log_level = "debug"

          service_registration "kubernetes" {}  
    affinity: |
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/name: vault
                app.kubernetes.io/instance: vault
                component: server
            topologyKey: failure-domain.beta.kubernetes.io/zone        
  injector:
    extraEnvironmentVars: 
      AGENT_INJECT_SET_SECURITY_CONTEXT: "false"
    image:
      repository: "docker.io/hashicorp/vault-k8s"
      tag: "0.11.0"      

