apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: external-secrets-subscription
  namespace: child-cluster-services 
  labels:
    app: external-secrets
  annotations:
      apps.open-cluster-management.io/git-branch: main
      apps.open-cluster-management.io/git-path: clusters/cluster-services/external-secrets/manifests/ 
      apps.open-cluster-management.io/reconcile-option: replace
spec:
  channel: child-cluster-services/external-secrets-channel
  placement:
    placementRef:
      kind: PlacementRule
      name: external-secrets-placement-1
#      apiGroup: apps.open-cluster-management.io