---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cwagent-prometheus-role-binding
subjects:
  - kind: ServiceAccount
    name: cwagent-prometheus
    namespace: amazon-cloudwatch
roleRef:
  kind: ClusterRole
  name: cwagent-prometheus-role
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cwagent-predeploy-job-role-binding
subjects:
  - kind: ServiceAccount
    name: cwagent-predeploy-job
    namespace: amazon-cloudwatch
roleRef:
  kind: Role
  name: cwagent-predeploy-job-role
  apiGroup: rbac.authorization.k8s.io
