kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: add-clusters-rb
subjects:
  - kind: ServiceAccount
    name: default
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: route-get
